- name: condtionl testing
  hosts: localhost
  tasks:
   - name: check robo shot exist or ot
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true

  - name: printing
    ansible.builtin.debug:
     msg: "{{user}}"

  - name: print exit status
    ansible.builtin.debug:
    msg: "status is {{user.rc}}"
     