- name: loops
  hosts: localhost
  become: yes
  tasks:
    - name: loop printed
      ansible.builtin.package:
        name: { { item } }
        state: present
      loop:
        - mysql
        - postfix
        - git
