- name: loops
  hosts: localhost
  become: yes
  tasks:
    - name: loop printed
      ansible.builtin.package:
        name: "{{item.name}}"
        state: "{{item.state}}"
      loop:
        - {name: 'mysql', state: 'present'}
        - {name: 'git', state: 'absent'}
        - {name: 'nginx', state: 'present'}
